- name: Echoing Vars with external vars file
  hosts: all
  gather_facts: false

  vars_files:
    - external_vars.yaml

  tasks:
    - name: Echo var
      ansible.builtin.command: /bin/echo "Hello World {{ msg_name }}"
      register: response

    - name: Print result
      ansible.builtin.debug:
        var: response
