- name: Echoing Vars
  hosts: all

  vars:
    msg_name: Supawit

  tasks:
    - name: Echo var
      ansible.builtin.command: /bin/echo "Hello World {{ msg_name }}"
      register: response

    - name: Print result
      ansible.builtin.debug:
        var: response
